name: "GUIX Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo:
        description: "elements repo"
        default: "ElementsProject/elements"
        required: true
      ref:
        description: "elements git ref"
        default: "refs/tags/elements-22.1.1-rc2"
        required: true
      tag:
        description: "the build tag"
        default: "elements-22.1.1-rc2"
        required: true

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [
          aarch64-linux-gnu,
          arm-linux-gnueabihf,
          powerpc64le-linux-gnu,
          powerpc64-linux-gnu,
          riscv64-linux-gnu,
          x86_64-apple-darwin18,
          x86_64-linux-gnu,
          x86_64-w64-mingw32,
        ]
    env:
      BUILD_TAG: elements-22.1.1-rc2
      #${{ inputs.tag }}
      HOST: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: debug
        run: pwd
      - name: "checkout elements"
        uses: actions/checkout@v3.3.0
        with:
          repository: "delta1/elements"
          #${{ inputs.repo }}
          path: "elements"
          ref: refs/tags/elements-22.1.1-rc2
          #${{ inputs.ref }}
      - name: gchr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.READ_TOKEN }}
      - name: "build script"
        run: |
          ./buildelements.sh
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/
  sums:
    name: sha256sums
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: output
      - name: script
        run: |
          ls -alht
          ls -alht output
          find output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 cat | tee sha256sum.txt
          find output/ -type f -print0 | env LC_ALL=C sort -z | cat | tee temp.txt
      - uses: actions/upload-artifact@v3
        with:
          name: sha256sum.txt
          path: sha256sum.txt
      - uses: actions/upload-artifact@v3
        with:
          name: temp.txt
          path: temp.txt
