name: "GUIX Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      repo:
        description: "elements repo"
        default: "ElementsProject/elements"
        required: true
      ref:
        description: "elements git ref"
        default: "refs/tags/elements-22.1.1-rc2"
        required: true
      tag:
        description: "the build tag"
        default: "elements-22.1.1-rc2"
        required: true

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [
          { arch: aarch64-linux-gnu, name: aarch64linuxgnu },
          { arch: arm-linux-gnueabihf, name: armlinuxgnueabihf },
          { arch: powerpc64le-linux-gnu, name: powerpc64lelinuxgnu },
          { arch: powerpc64-linux-gnu, name: powerpc64linuxgnu },
          { arch: riscv64-linux-gnu, name: riscv64linuxgnu },
          { arch: x86_64-apple-darwin18, name: x86_64appledarwin18 },
          { arch: x86_64-linux-gnu, name: x86_64linuxgnu },
          { arch: x86_64-w64-mingw32, name: x86_64w64mingw32 },
        ]
    env:
      BUILD_TAG: elements-22.1.1-rc2
      #${{ inputs.tag }}
      HOST: ${{ matrix.host.arch }}
      NAME: ${{ matrix.host.name }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: debug
        run: pwd
      - name: "checkout elements"
        uses: actions/checkout@v3.3.0
        with:
          repository: "delta1/elements"
          #${{ inputs.repo }}
          path: "elements"
          ref: refs/tags/elements-22.1.1-rc2
          #${{ inputs.ref }}
      - name: gchr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.READ_TOKEN }}
      - name: "build script"
        run: |
          ./buildelements.sh
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/
  sums:
    name: "sums"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: temp
        run: |
          echo "here"
          echo ${{ steps.build.outputs.aarch64linuxgnu }}
          echo ${{ steps.build.outputs.armlinuxgnueabihf }}
          echo ${{ steps.build.outputs.powerpc64lelinuxgnu }}
          echo ${{ steps.build.outputs.powerpc64linuxgnu }}
          echo ${{ steps.build.outputs.riscv64linuxgnu }}
          echo ${{ steps.build.outputs.x86_64appledarwin18 }}
          echo ${{ steps.build.outputs.x86_64linuxgnu }}
          echo ${{ steps.build.outputs.x86_64w64mingw32 }}
          echo "there"
