name: "Guix Build"

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      repo:
        description: "elements repo"
        default: "ElementsProject/elements"
        required: true
      ref:
        description: "elements git ref"
        default: "refs/tags/elements-22.1.1"
        required: true
      tag:
        description: "the build tag"
        default: "elements-22.1.1"
        required: true

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [
          aarch64-linux-gnu,
          arm-linux-gnueabihf,
          powerpc64le-linux-gnu,
          powerpc64-linux-gnu,
          riscv64-linux-gnu,
          x86_64-apple-darwin18,
          x86_64-linux-gnu,
          x86_64-w64-mingw32,
        ]
    env:
      BUILD_TAG: ${{ inputs.tag }}
      HOST: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: debug
        run: |
          pwd
          whoami
      - name: "checkout elements"
        uses: actions/checkout@v3.3.0
        with:
          repository: ${{ inputs.repo }}
          path: "elements"
          ref: ${{ inputs.ref }}
      - name: gchr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.READ_TOKEN }}
      - name: "build script"
        run: |
          # ./buildelements.sh
          mkdir output
          echo $HOST > output/$HOST.txt
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output/
      - name: cleanup
        run: |
          WHO=$(whoami)
          sudo chown -R $WHO:$WHO $(pwd)
  sums:
    name: sha256sums
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_TAG: ${{ inputs.tag }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: output
      - name: script
        run: release.sh
      - uses: actions/upload-artifact@v3
        with:
          name: sha256sums.txt
          path: sha256sums.txt
