# run on workflow
# provide tag/branch
# checkout this repo
# clone elements

name: "GUIX Build"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "elements git ref"
        default: "refs/heads/elements-22.1"
        required: true
      tag:
        description: "the build tag"
        default: "elements-22.1"
        required: true

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    env:
      build_tag: ${{ inputs.tag }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: debug
        run: pwd
      - name: "checkout elements"
        uses: actions/checkout@v3.3.0
        with:
          repository: "ElementsProject/elements"
          path: "elements"
          ref: ${{ inputs.ref }}
      - name: "build script"
        run: ./buildelements.sh
