# run on workflow
# provide tag/branch
# checkout this repo
# clone elements

name: "GUIX Build"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "elements git ref"
        default: "refs/heads/elements-22.1"
        required: true
      tag:
        description: "the build tag"
        default: "elements-22.1"
        required: true

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    env:
      BUILD_TAG: ${{ inputs.tag }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: debug
        run: pwd
      - name: "checkout elements"
        uses: actions/checkout@v3.3.0
        with:
          repository: "ElementsProject/elements"
          path: "elements"
          ref: ${{ inputs.ref }}
      - name: gchr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.READ_TOKEN }}
      - name: "build script"
        run: ./buildelements.sh
